// <auto-generated />
using System;
using DakaDiningBackend.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DakaDiningBackend.Migrations
{
    [DbContext(typeof(DakaContext))]
    [Migration("20231211000642_StartAndEndTimes")]
    partial class StartAndEndTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DakaDiningBackend.Entities.OfferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<bool>("Purchased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchasedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferedById");

                    b.HasIndex("PurchasedById");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.RequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Filled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilledById")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilledById");

                    b.HasIndex("RequestedById");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.UserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MealSwipes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealsOffered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.OfferEntity", b =>
                {
                    b.HasOne("DakaDiningBackend.Entities.UserEntity", "OfferedBy")
                        .WithMany("Offers")
                        .HasForeignKey("OfferedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DakaDiningBackend.Entities.UserEntity", "PurchasedBy")
                        .WithMany("OffersFilled")
                        .HasForeignKey("PurchasedById");

                    b.Navigation("OfferedBy");

                    b.Navigation("PurchasedBy");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.RequestEntity", b =>
                {
                    b.HasOne("DakaDiningBackend.Entities.UserEntity", "FilledBy")
                        .WithMany("RequestsFilled")
                        .HasForeignKey("FilledById");

                    b.HasOne("DakaDiningBackend.Entities.UserEntity", "RequestedBy")
                        .WithMany("Requests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilledBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.SessionEntity", b =>
                {
                    b.HasOne("DakaDiningBackend.Entities.UserEntity", "User")
                        .WithOne("Session")
                        .HasForeignKey("DakaDiningBackend.Entities.SessionEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DakaDiningBackend.Entities.UserEntity", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("OffersFilled");

                    b.Navigation("Requests");

                    b.Navigation("RequestsFilled");

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
